name: Pre-Commit

on:
  pull_request:
    branches: [main, master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: pre-commit/action@v3.0.1
